### ISSUE TITLE
about use in mac

### ISSUE THREAD

**Issue by tssailzz8** [marzent/IINACT#20]
my frient ues it in china mac,it can  not get the server.
251|2022-09-28T00:46:04.6446810+09:00|RawCaptureSocket: Did not detect Idle process, using TCP socket instead of IP socket for wine compatability.|e062702f94afc441
251|2022-09-28T00:47:22.0000000+09:00|UNKNOWN WORLD ID [1FF]|3bc62143fc2e0734
and this is log
[Network_26606_20220928.log](https://github.com/marzent/IINACT/files/9663252/Network_26606_20220928.log)

**Comment by marzent** [comment]
Is your friend on at least v0.4 ?

**Comment by tssailzz8** [comment]
yes

**Comment by Bluefissure** [comment]
> my frient ues it in china mac,it can not get the server.

Do you/your friend use it for intl client in China or for the CN client?

I doubt whether it works on the modded FFXIV_ACT_Plugin for CN client, I will have a test later.

**Comment by marzent** [comment]
I unfortunately do not have a Chinese client to test upon, but there are changes to Machina at the very least that need to happen, in order for it to run; this should have not much to do with running on macOS via wine.

Since I can't develop or provide support for the Chinese version I will close this issue, however PRs are always welcome :)
