### ISSUE TITLE
What’s the update flow?

### ISSUE THREAD

**Issue by seivan** [marzent/IINACT#26]
I know there’s no auto update but is the expectation that updated releases of XIVOnMac will have updated versions that need to be installed again manually or will installing new versions of XIVOnMac automatically replace older with newer on launch?

**Comment by marzent** [comment]
The update flow is fully automatic for XOM (independent of XOM version) and future versions will have "an update is available" warning as well

**Comment by marzent** [comment]
XOM is short for XIVOnMac and the update "update IINACT" option does not exist since XOM always enforces the latest version (see https://github.com/marzent/XIV-on-Mac/blob/main/XIV%20on%20Mac/AddOns/IINACT.swift).

IINACT is completely independent from ACT but it does require the FFXIV_ACT_Plugin made by Ravahn (closed-source) and a heavily modified OverlayPlugin for modern .NET (maintained by me, but I try to keep it close to https://github.com/OverlayPlugin/OverlayPlugin)
