### ISSUE TITLE
Just wondering why?

### ISSUE THREAD

**Issue by Battler624** [marzent/IINACT#33]
Just wondering why shouldn't we run this as administrator?

**Comment by Braccae** [comment]
Bad practice mostly. Think of it like this, you wouldn't give your pizza delivery person the key to your home, right? They don't need complete access like that to do their job. It might make it easier for them if you don't answer the door or something but that's a lot of trust to give to a stranger, innit? Opening programs as administrator gives them full access to your PC and as we just recently saw with ghade, developers are still people at the end of the day and are capable of making poor decisions. Not saying they will, but other things can happen as well such as the github keys getting lost/stolen and a malicious payload inserted into the code, etc and running the program as admin makes things like that 1000x easier to pull off. 

It's just better to not leave the front door wide open like that in the first place if you don't absolutely need to.

**Comment by marzent** [comment]
“Every program and every user of the system should operate using the least set of privileges necessary to complete the job.”
—Saltzer, J.H. AND Schroeder, M.D., “The Protection of Information in Computer Systems,” Proceedings of the IEEE, vol. 63, no. 9, Sept 1975.

Also there is a high possibility that the parse file being created or a config file will become unusable for a normal user.

**Comment by Battler624** [comment]
Sorry for re-opening this, then I'd like to change my question, If the game is already running as admin, would I need to run IINACT as admin for it to recognize the game? or can it work completely from user while the game is as admin?

**Comment by cozyGalvinism** [comment]
Besides the fact that you shouldn't be running games as admin *at all*, IINACT *should* be able to recognize the game. That said, running IINACT as admin is most likely not supported.

**Comment by Dormanil** [comment]
You see, this is another reason for why not to run something as an admin: 
A: I would not be surprised that some of your ffxiv user data (configs, screenshot folder etc.) can now only be written by an administrator. 
B: Anything that wants to interact with the game now needs to run as admin: Want Steam or Discord to render their overlay? Yeah, those now need to run as admin as well. Since IINACT only reads game data, and doesn't write any data into the game, you should be fine with the game run as admin, but that still doesn't invalidate all the other things wrong with starting the game as admin.

**Comment by Battler624** [comment]
Is there a way to test if all functions of iinact would be good?
