### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by x4dr** [marzent/IINACT#34]
the how to build section could use some work. i assume the FFXIV_ACT_Plugin.dll is the one that act usually uses?
what SDK files? where do i get them
how do i build the IINACT project
assuming i build it, what do i do to install/run it

**Comment by cozyGalvinism** [comment]
> i assume the FFXIV_ACT_Plugin.dll is the one that act usually uses?
Correct.

> what SDK files? where do i get them
[Here, in the Releases folder.](https://github.com/ravahn/FFXIV_ACT_Plugin)

> how do i build the IINACT project
Assuming you use the dotnet CLI, it should be as simple as running `dotnet build`.

> assuming i build it, what do i do to install/run it
You just run it. It works the same as the IINACT you download from the Releases.

I agree that the section could be improved but I've built it today for the first time with the same instructions, so they aren't terribly unclear, it's just a matter of knowing how the ACT plugin is distributed and to clone the repository recursively in order to also have the submodules on your disk. The rest is basically the same for every .NET Core application.

**Comment by marzent** [comment]
Actually it used to be that you need the ffxiv act plugin to build, but current IINACT will build against stubs and fetch the real dlls during runtime.

The build is like @cozyGalvinism said just `dotnet build`, nothing more needed.

I will update the readme to make it more clear though.
