### ISSUE TITLE
Relation to Advanced Combat Tracker

### ISSUE THREAD

**Issue by EQAditu** [marzent/IINACT#9]
I just wanted to say that I don't condone this.

You decompiled ACT, stole parts of its code and released it as "open source" under your own name.  You never once approached me about doing this for permission, advice or otherwise.  I'm no mystical open source spirit-guide... but I don't think this project follows the tenants of open source software like your website suggests.

That's all I have to say.  Bye then.

**Comment by marzent** [comment]
If you take a look at the NotACT Project, you will notice that the entire API surfaced is minimal as in if you were to remove one of the data types, OverlayPlugin or the FFXIV Plugin or both will stop working properly.

In that sense I believe that it is reverse engineering since it was not meant to replicate ACT, the program, but rather only whatever plugins reference in order to function.

All calculations were reimplemented in LINQ not using the loops ACT uses. You wouldn't call wine stealing Microsoft software just because it reimplements the same functions or was done by inspecting Microsoft assembly.

Having said that C# does make reverse engineering so simple that the decompilation is close to the source (I presume I have never seen it) and probably some parts look identical.

I did approach you multiple times in order to make it better integrate with wine, but never really got any response which resulted in actual changes.

Since this seems to be a rather heated topic it is probably best to agree to disagree...
